AC-1964 Sanitize inputs
AI4VBH/AIDE-api pull request #130
Opened 2023-04-06 12:54 UTC by lillie-dae

### Description

Fixes # .

A few sentences describing the changes proposed in this pull request.

### Status
**Ready/Work in progress/Hold**

### Types of changes

- [ ] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New unit tests added to cover the changes.
- [ ] New e2e tests added to cover the changes. (If it has been decided these will not be added with the PR, a seperate ticket **must** be created and linked in the ticket below before merge)
- [ ] All tests passed locally.

2023-04-06 13:01 UTC, DanielNuttall-AD approved these changes

2023-04-11 08:44 UTC, rowellx68 approved these changes

2023-04-11 08:50 UTC, RemakingEden requested changes

2023-04-11 08:50 UTC, RemakingEden commented on src/modules/clinical-review/__snapshots__/clinical-review.service.spec.ts.snap
> +exports[`WorkflowsService acknowledgeClinicalReview sanatizes input returns expected result 1`] = `undefined`;
Is this the expected result? The one above is also undefined. I think this should probably have a real response snapshot

2023-04-11 10:52 UTC, lillie-dae commented on src/modules/clinical-review/clinical-review.service.spec.ts
> +      expect(review.reason).toBe('all good');
It mutates the object values so its fine to check this object, as its object that goes to the service as the parameters.

2023-04-11 11:13 UTC, mehranrashid approved these changes

2023-04-12 10:28 UTC, lillie-dae commented on src/modules/clinical-review/__snapshots__/clinical-review.service.spec.ts.snap
> +exports[`WorkflowsService acknowledgeClinicalReview sanatizes input returns expected result 1`] = `undefined`;
removed this snapshot just tested in code it returns put value.

2023-04-12 10:31 UTC, merged